"""系统提示词（已迁移到 src/promts）"""

from promts import (
    SYSTEM_PROMPT,
    JOIN_SUGGEST_PROMPT,
    INTENT_ANALYSIS_PROMPT,
    SQL_GENERATION_PROMPT,
    SQL_VALIDATION_PROMPT,
    ANSWER_REFINEMENT_PROMPT,
)

__all__ = [
    "SYSTEM_PROMPT",
    "JOIN_SUGGEST_PROMPT",
    "INTENT_ANALYSIS_PROMPT",
    "SQL_GENERATION_PROMPT",
    "SQL_VALIDATION_PROMPT",
    "ANSWER_REFINEMENT_PROMPT",
]
